### ISSUE TITLE
FS: Authorization with Gmail API for the user

### ISSUE THREAD

**Issue by bonnieli** [hatchways/team-autumn#12]
- Modify the user object to contain gmail authorization information
- If the user is not authorized when they open the web app, a material UI dialog (https://material-ui.com/components/dialogs/) if the user has not connected their account with their gmail, that pops up
- The auth with gmail button will open up gmail and redirect back the React front-end 
- The React front-end will send the auth token generated back

How to connect Gmail:
- https://developers.google.com/gmail/api/auth/about-auth
- https://developers.google.com/identity/protocols/OAuth2?hl=en_US
- Specific to web apps - https://developers.google.com/identity/protocols/OAuth2WebServer

**Task 1**:
- Method to get the authorization URL that you need to redirect the user to when they click the Google button on the front-end. I recommend having a route on the back-end to get the authorization url, and when someone clicks the button, you make an API call to that route and then you redirect the user manually to that route.

**Task 2**:
- Once someone fills out the authorization URL, they will be redirected back to your app. You need to then write another back-end API call to update get the user credentials information and then store it to the database.

I found this resource:
https://developers.google.com/gmail/api/auth/web-server
look at get_authorization_url - it actually has the code for step 1
look at exchange_code and get_credentials for step 2. In step 2, in the redirection URL, you will be passed a state and authorization code. You will have to write code on the front-end to send those detials to the back-end, and then in the back-end use some of the code in the resource to get the credentials, and then write an implementation to store the credentials in the back-end

**Comment by skassam21** [comment]
<img width="537" alt="68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563373431326662323138363837353934343335646363622f33656435396234302d643563302d346533342d623866312d353735346432373037336539" src="https://user-images.githubusercontent.com/5060546/95907544-b25b7f00-0d69-11eb-8ce5-93951e17a757.png">
<img width="485" alt="68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563373431326662323138363837353934343335646363622f66323137316332362d316335632d343739332d613061622d663834393762363638343733" src="https://user-images.githubusercontent.com/5060546/95907553-b5ef0600-0d69-11eb-8be4-9bb7bc7a67f6.png">
<img width="470" alt="68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563373431326662323138363837353934343335646363622f37623836306634652d323830392d343830612d623564332d303632356665343466353936" src="https://user-images.githubusercontent.com/5060546/95907562-ba1b2380-0d69-11eb-9713-4e9269a1dba4.png">
